# Generated by Django 4.1 on 2022-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_todolist',
            fields=[
                ('taskid', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('deadline', models.CharField(max_length=50)),
                ('mentor', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_todolist',
            },
        ),
    ]
