# Generated by Django 4.1 on 2022-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_todolist',
            name='deadline',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_todolist',
            name='time',
            field=models.TimeField(max_length=50),
        ),
    ]
